---
- name: install httpd
  hosts: all
  tasks:
    - name: install httpd server
      yum:
        name: httpd
        state: present
    - name: create an index.html
      copy: 
        content: 'welcome to the thesis webserver'
        dest: /var/www/html/index.html
    - name: start the service
      service:
        name: httpd
        state: started
        enabled: true
   
