---
- name: Iam going to create users and groups using this playbook
  hosts: all
  tasks:
   - name: create an admin group
     group:
      name: admin
      state: present
   - name: create admin users
     user:
      name: tinashe 
      comment: admin
      groups: admin
